repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      # Lint + autofix
      - id: ruff
        args: [--fix]
      # Optional: ensure formatting consistency
      - id: ruff-format